---

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ virtualenv_path }} requirements={{ requirements_file }}

- name: Run Django South migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_south_migration
  tags:
    - django
    - django_migrate

- name: Install web assets
  apt: name={{ item }} update_cache={{ update_apt_cache }} state=installed
  with_items:
    - node
    - npm

- name: Install bower
  npm: name=bower global=yes state=present

- name: Run Django bower
  django_manage:
    command: bower_install
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_collectstatic
  tags:
    - django
    - django_collectstatic
